[[redirects]]
  from = "/channels/*"
  to = "https://channels.nixos.org/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/releases/channels/*"
  to = "https://channels.nixos.org/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/releases/nixos/channels/*"
  to = "https://channels.nixos.org/nixos/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/releases/*/install"
  to = "https://releases.nixos.org/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/releases/*"
  to = "https://releases.nixos.org/:splat"
  status = 301
  force = true

# [[redirects]]
#   from  = "/nix/install"
#   to = "https://channels.nixos.org/nix-latest/install"
#   status = 301
#   force = true

[[redirects]]
  from  = "/hydra"
  to = "https://github.com/NixOS/hydra"
  status = 301
  force = true

[[redirects]]
  from  = "/nixops"
  to = "https://github.com/NixOS/nixops"
  status = 301
  force = true
